// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJSh6ISeMMfuAzxWLqpxJIjx18OlyDcQg',
    appId: '1:1042877028872:web:3623b7d3b68b91ea7ecfbd',
    messagingSenderId: '1042877028872',
    projectId: 'expense-calculator1',
    authDomain: 'expense-calculator1.firebaseapp.com',
    storageBucket: 'expense-calculator1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-2GdwpZQze68Wq95jkXq43vXscbPVElU',
    appId: '1:1042877028872:android:cd2abffc9cad63ad7ecfbd',
    messagingSenderId: '1042877028872',
    projectId: 'expense-calculator1',
    storageBucket: 'expense-calculator1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUMR7-LwNnec6s5ecIe4jOEKbynQsYXbE',
    appId: '1:1042877028872:ios:9d04e0cf6d6c48f37ecfbd',
    messagingSenderId: '1042877028872',
    projectId: 'expense-calculator1',
    storageBucket: 'expense-calculator1.firebasestorage.app',
    iosBundleId: 'com.example.expenseCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMR7-LwNnec6s5ecIe4jOEKbynQsYXbE',
    appId: '1:1042877028872:ios:9d04e0cf6d6c48f37ecfbd',
    messagingSenderId: '1042877028872',
    projectId: 'expense-calculator1',
    storageBucket: 'expense-calculator1.firebasestorage.app',
    iosBundleId: 'com.example.expenseCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJSh6ISeMMfuAzxWLqpxJIjx18OlyDcQg',
    appId: '1:1042877028872:web:e09917b2527f466f7ecfbd',
    messagingSenderId: '1042877028872',
    projectId: 'expense-calculator1',
    authDomain: 'expense-calculator1.firebaseapp.com',
    storageBucket: 'expense-calculator1.firebasestorage.app',
  );
}
